# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14w3l6kvBjYOfUmcv6yJGPyqcenMYiID2
"""

!pip install python-telegram-bot
!pip install adafruit-io
from telegram.ext import Updater,CommandHandler,MessageHandler,Filters
from Adafruit_IO import Client,Data
import os

def turnoffthelight(update, context):
  context.bot.send_message(chat_id=update.effective_chat.id, text="Bulb turned off")
  context.bot.send_photo(chat_id=update.effective_chat.id,photo='https://www.google.co.in/url?sa=i&url=https%3A%2F%2Fwww.123rf.com%2Fphoto_48123160_stock-vector-bright-glowing-incandescent-light-bulb-on-a-white-background.html&psig=AOvVaw1CM2JwdO30lTYALZS74qv5&ust=1600279369911000&source=images&cd=vfe&ved=0CAIQjRxqFwoTCJiFr63f6-sCFQAAAAAdAAAAABAD')
  send_value(0)
def turnonthelight(update, context):
  context.bot.send_message(chat_id=update.effective_chat.id, text="Bulb turned on")
  context.bot.send_photo(chat_id=update.effective_chat.id,photo='https://www.google.co.in/url?sa=i&url=https%3A%2F%2Fwww.123rf.com%2Fphoto_48123160_stock-vector-bright-glowing-incandescent-light-bulb-on-a-white-background.html&psig=AOvVaw3yjACHWfoCfpBRg94DiNkB&ust=1600279074782000&source=images&cd=vfe&ved=0CAIQjRxqFwoTCPi77KDe6-sCFQAAAAAdAAAAABAD')
  send_value(1)

def send_value(value):
  feed = aio.feeds('ashaj')
  aio.send_data(feed.key,value)

def input_message(update, context):
  text=update.message.text
  if text == 'turnonthelight':
    send_value(1)
    context.bot.send_message(chat_id=update.effective_chat.id,text="Bulb turned on")
    context.bot.send_photo(chat_id=update.effective_chat.id,photo='https://www.google.co.in/url?sa=i&url=https%3A%2F%2Fwww.123rf.com%2Fphoto_48123160_stock-vector-bright-glowing-incandescent-light-bulb-on-a-white-background.html&psig=AOvVaw1CM2JwdO30lTYALZS74qv5&ust=1600279369911000&source=images&cd=vfe&ved=0CAIQjRxqFwoTCJiFr63f6-sCFQAAAAAdAAAAABAD')
  elif text == 'turnoffthelight':
    send_value(0)
    context.bot.send_message(chat_id=update.effective_chat.id,text="Bulb turned off")
    context.bot.send_photo(chat_id=update.effective_chat.id,photo='https://www.google.co.in/url?sa=i&url=https%3A%2F%2Fwww.vectorstock.com%2Froyalty-free-vector%2Fobject-bulb-off-vector-1858972&psig=AOvVaw15IuAn-EMouhd-qQ0y12_E&ust=1600279227128000&source=images&cd=vfe&ved=0CAIQjRxqFwoTCNj1mune6-sCFQAAAAAdAAAAABAD')

def start(update,context):
  start_message='''
/turnoff the light or 'turn off':To turn off the bulb ,sends value=0 in feed
/turnon the light or 'turn on'  :To turn on the bulb ,sends value=1 in feed
'''
  context.bot.send_message(chat_id=update.effective_chat.id, text=start_message)

ADAFRUIT_IO_USERNAME =  os.getenv('ASHASHERIN')
ADAFRUIT_IO_KEY = os.getenv('aio_zxbU99YhLwLjCrFQQQl2TFbUvYS0')
TOKEN = os.getenv('1273321980:AAG-ssXNYmAqa3_kvtqUOzbIIGu5nOCXuNI')

aio = Client('ASHASHERIN','aio_zxbU99YhLwLjCrFQQQl2TFbUvYS0')
updater=Updater('1273321980:AAG-ssXNYmAqa3_kvtqUOzbIIGu5nOCXuNI',use_context=True)
dispatcher = updater.dispatcher
dispatcher.add_handler(CommandHandler('turnoffthelight',turnoffthelight))
dispatcher.add_handler(CommandHandler('turnonthelight',turnonthelight))
dispatcher.add_handler(CommandHandler('start',start))
dispatcher.add_handler(MessageHandler(Filters.text & (~Filters.command),input_message))
updater.start_polling()
updater.idle()